### ISSUE TITLE
throw Card button not work in the example

### ISSUE THREAD

**Issue by skumblue** [ssanjun/react-swing#10]
Hi!

I want to throw cards with a control button (like yours [example](http://ssanjun.github.io/examples/react-swing))
<img width="373" alt="screen shot 2017-08-14 at 1 00 43 pm" src="https://user-images.githubusercontent.com/3875593/29280173-8aeccb44-80f0-11e7-9741-2bd19a5b3ad8.png">

But I downloaded the [example code](https://github.com/ssanjun/react-swing/tree/master/Examples) and installed on my machine, **but the button "throw Card" not work**. 

The console show:
<img width="1264" alt="screen shot 2017-08-14 at 1 04 39 pm" src="https://user-images.githubusercontent.com/3875593/29280310-1c378ba2-80f1-11e7-8a8a-6d150f055949.png">

I think that the problem is `throwDirection: Symbol(INVALID)`, then I changed the next line of code located in **index.js:35**:
`card.throwOut(100, 200);`

To:
`card.throwOut(100, 200, Symbol('LEFT'));`

And To:
`card.throwOut(100, 200, 1);`

But not work...

How can I do it?

Thank you!

**Comment by ssanjun** [comment]
Hi @skumblue !
I check it, and It was bug. So I fix it
please Check this commit [https://github.com/ssanjun/react-swing/commit/4c07e4a4458da0188fda151f7eb2efe2d2109363](https://github.com/ssanjun/react-swing/commit/4c07e4a4458da0188fda151f7eb2efe2d2109363)

Thanks!

**Comment by skumblue** [comment]
@ssanjun thanks!
