### ISSUE TITLE
how can I throw the top card in the throwCard method?

### ISSUE THREAD

**Issue by dmoli** [ssanjun/react-swing#11]
Hi!

When I press **Throw Card** button always call the same card (card2):

*Examples/index.js:28*
` const target = this.refs.stack.refs.card2;`

**How can I call always to the top card and delete it from stack?** (To simulate Tinder feature)

I tried:
*Examples/index.js:28*
` const target = this.refs.stack.refs[0];`

But not work...

I hope your comment, thanks!

**Comment by ssanjun** [comment]
Hi @skumblue 
You know, 'refs' is not Array, it is Object in React.
So if you want to throw other card then access to 'refs' on key like 'card2'.
And You will be try this 'console.log(this.refs.stack.refs)'. 
you will saw 'this.refs.stack.refs' Object.

Thanks!

**Comment by skumblue** [comment]
@ssanjun Ok.

And how can I delete a card from the stack? (like a Tinder feature)

Thanks!

**Comment by ssanjun** [comment]
@skumblue 
I think it is possible just DOM control.

like this..
Examples/index.js
```javascript

// throwOut Method
    throwCard() {
        // Swing Card Directions
        console.log('Swing.DIRECTION', Swing.DIRECTION);

        // Swing Component Childrens refs
        const target = this.refs.stack.refs.card2;

        // get Target Dom Element
        const el = ReactDOM.findDOMNode(target);

        // stack.getCard
        const card = this.state.stack.getCard(el);

        // throwOut method call
        card.throwOut(100, 200, Swing.DIRECTION.RIGHT);
        el.style.display = 'none';
    }

```

if you want to delete card when throwing animation was end then you check this card event ['throwoutend'](https://github.com/ssanjun/react-swing#component-event-props)!

Thanks!
