### ISSUE TITLE
Can I edit the velocity in throwOut method?

### ISSUE THREAD

**Issue by dmoli** [ssanjun/react-swing#12]
Hi again!

A doubt, is possible edit the velocity of the transition when the card is thrown from click the control button?

index.js:37:
`card.throwOut(100, 200, Swing.DIRECTION.RIGHT);`

Thanks @ssanjun!

**Comment by ssanjun** [comment]
Yeah. Hi again too!
react-swing is using [swing](https://github.com/gajus/swing). And swing is using [Rebound](https://github.com/facebook/rebound-js) as animations.

And animation speed settings is in reboud-js.

And check [rbound-js API](http://facebook.github.io/rebound-js/docs/rebound.html)
```javascript
createSpring: function(tension, friction) {
      var springConfig;
      if (tension === undefined || friction === undefined) {
        springConfig = SpringConfig.DEFAULT_ORIGAMI_SPRING_CONFIG;
      } else {
        springConfig =
          SpringConfig.fromOrigamiTensionAndFriction(tension, friction);
      }
      return this.createSpringWithConfig(springConfig);
    },
```
createSpring Method receive two arguments as 'tension' and 'friction'. 
Maybe you will be able to control the speed with these two parameters.

But unfortunately swing will be setting two arguments as static value when you will call createCard method.
check this [line](https://github.com/gajus/swing/blob/master/src/Card.js#L68)

So.. I think it is impossible.
I will look for another way.

Thanks.

**Comment by skumblue** [comment]
@ssanjun Hi!

I understand that I can´t modify the speed when the button is clicked.

But... can I modify the speed when the cards are thrown out with **drag event**?

Thank again!

**Comment by ssanjun** [comment]
@skumblue Hi!
Do you mean that can modify velocity during mouse drag?
I think it is just mouse move speed.
Or you mean that card moving delay after mouse drag?

Give me more information..
