### ISSUE TITLE
Swipe top throw card out of viewport

### ISSUE THREAD

**Issue by dmoli** [ssanjun/react-swing#13]
Hi @ssanjun!

Hey, in your [example](http://ssanjun.github.io/examples/react-swing/) when I swipe top, the card is keeping in the viewport. It is perfect!

But in the [example to download](https://github.com/ssanjun/react-swing/tree/master/Examples), when I swipe top, the card is thrown out to the viewport...

<img width="1163" alt="screen shot 2017-08-16 at 4 29 48 pm" src="https://user-images.githubusercontent.com/3875593/29381582-1844d3c8-82a0-11e7-9c51-6809090af3c8.png">

How can I solve this?

Really, thank you very much!

**Comment by ssanjun** [comment]
Hi @skumblue 
it is setting of Swing component.
Check this [section](https://github.com/ssanjun/react-swing#component-props)
if you want to allowed specific direction then you will setting 'allowedDirections' value in config object.

```javascript
<Swing
    config={{
        allowedDirections: [Swing.DIRECTION.LEFT, Swing.DIRECTION.RIGHT]
    }}
>

```

it will be work.
Thanks!

**Comment by skumblue** [comment]
@ssanjun my friend, thank you very much!

**Comment by Raikhen** [comment]
Hi @ssanjun, Swing.DIRECTION is undefined, at least in the React 16 version...
