### ISSUE TITLE
Can I modify when the card out of the viewport?

### ISSUE THREAD

**Issue by dmoli** [ssanjun/react-swing#14]
Hello!

I need the cards to be thrown out of the viewport just in this movement:

<img width="1280" alt="screen shot 2017-08-19 at 2 13 40 pm" src="https://user-images.githubusercontent.com/3875593/29488798-94044134-84e8-11e7-9ce0-614456a1e31e.png">

I currently have to drag them a lot to get them out of the viewport ...

<img width="1280" alt="screen shot 2017-08-19 at 2 13 55 pm" src="https://user-images.githubusercontent.com/3875593/29488802-a198e23c-84e8-11e7-98a7-b92511df0c80.png">

Can it be configured?

Thank you!

**Comment by ssanjun** [comment]
Hi @skumblue 
it is setting of Swing component.
Check this [section](https://github.com/ssanjun/react-swing#component-props).
And Read this [section](https://github.com/gajus/swing#configuration)

```javascript
<Swing
config={{
    throwOutConfidence: (xOffset, yOffset, element) => {
        const xConfidence = Math.min(Math.abs(xOffset) / element.offsetWidth, 1);
        const yConfidence = Math.min(Math.abs(yOffset) / element.offsetHeight, 1);
    
        // 0.5 is value you want.
        if (Math.max(xConfidence, yConfidence) > 0.5) {
            return 1;
        }
        return Math.max(xConfidence, yConfidence);
    }
}}
...
/>
```

Thanks!
