### ISSUE TITLE
this.state on min/maxThrowOutDistance

### ISSUE THREAD

**Issue by CasperEngl** [ssanjun/react-swing#17]
```
config={{
  minThrowOutDistance: this.state.minDistance,
  maxThrowOutDistance: this.state.maxDistance,
}}
```
Setting the state later will result in these values being set to the default state values. Component rerender happens, but the values don't seem to do the same.

<img width="544" alt="screenshot at may 31 11-26-18 am" src="https://user-images.githubusercontent.com/11478629/40774279-7c7c3f86-64c5-11e8-96bf-1c7e9be7767c.png">

"SWING CONFIG" comes from the rerender when the state changes. "THROW HANDLER" is logged when I tried throwing the component.

**Comment by ssanjun** [comment]
Hi! @CasperEngl !
I checked Swing.js source.

check it this line 
https://github.com/gajus/swing/blob/c7cebdf9e3fddb51509b645b6803760f86b3c930/src/Card.js#L64
```javascript
// https://github.com/gajus/swing/blob/master/src/Card.js#L64
const construct = () => {
    card = {};
    config = Card.makeConfig(stack.getConfig()); // this line
    eventEmitter = Sister();
    springSystem = stack.getSpringSystem();
    springThrowIn = springSystem.createSpring(250, 10);
    ....
```

When a Stack is created, a Card is created by the Stack. and Card will create with config from Stack. it will be immutable. so you want to change to config then i guess you must be recreate stack.

I hope it was helpful.
