### ISSUE TITLE
Accessing PropTypes from the main React package is deprecated

### ISSUE THREAD

**Issue by bogdan-calapod** [ssanjun/react-swing#7]
Getting this warning using the latest version of create-react-app (react 15.5.4, react-scripts 0.9.5)

Seems that the problem is in the Swing.js file

**Comment by ssanjun** [comment]
Thanks. @bogdan-calapod

**Comment by ssanjun** [comment]
react-swing update to 1.0.0 
check this [commit](https://github.com/ssanjun/react-swing/commit/e1b0f1f64bb617ea684dc9c4fe082240b4aa77c7)

thanks.
